name: Feature Request
description: Propose a feature for the TLS Requests
title: "[Feature Request]: "
labels: ["enhancement"]
body:

- type: markdown
  attributes:
    value: |
      - Write a proposal title above.
      - Search [open](https://github.com/thewebscraping/tls-requests/issues?q=is%3Aopen) and [closed](https://github.com/thewebscraping/tls-requests/issues?q=is%3Aclosed) proposals to ensure the feature has not already been suggested.

- type: textarea
  attributes:
    label: Describe the feature / enhancement and how it would improve things
    description: |
      - Dont overcomplicate
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe how your proposal will work, with code and/or pseudo-code
  validations:
    required: true
