__title__ = "wrapper-tls-requests"
__description__ = "A powerful and lightweight Python library for making secure and reliable HTTP/TLS Fingerprint requests."
__url__ = "https://github.com/thewebscraping/tls-requests"
__author__ = "Tu Pham"
__author_email__ = "thetwofarm@gmail.com"
__version__ = "1.1.3"
__license__ = "MIT"
