name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Publish PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Build package
        run: |
          python -m pip install -U pip build setuptools twine
      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload --skip-existing dist/*
